### ISSUE TITLE
Adicionar Guia de Contribuição

### ISSUE THREAD

**Issue by marcos-vinicius14** [PedroHMeireles2001/GamifyHealth#1]
Criar um guia de contribuição no README seria muito útil para quem quiser contribuir no projeto. Adicionar as convenções de commits e tudo que precisa para começar a contribuir. Isso seria muito útil para quem vem contribuir no projeto e também ajuda na organização, visto que todos terão um padrão para seguir. Por ser o criador, Pedro, você é a melhor pessoa para fazer isso.

**Comment by PedroHMeireles2001** [comment]
Atualizei o Readme.md e adicionei mais informações, obrigado pelo dica

**Comment by marcos-vinicius14** [comment]
De nada! É um prazer ajudar
