### ISSUE TITLE
Sem permissão para fazer o push.

### ISSUE THREAD

**Issue by ghost** [PedroHMeireles2001/GamifyHealth#2]
Estou tentanto fazer um pull request porem sempre quando faço "git push" esse erro aparece:
![image](https://github.com/PedroHMeireles2001/GamifyHealth/assets/90799507/f9a4aee9-6a92-4b36-8e62-30bb85448bb6)
Será que pode ver as configurações de permissão para os colaboradores? Realmente não sei se esse problema é da minha máquina ou do proprio repositório.

**Comment by PedroHMeireles2001** [comment]
Tenta fazer um fork e um pull request depois.
Caso não consiga, tente me contatar pelo discord (pemei)

**Comment by ghost** [comment]
Vou fazer isso amanha! Caso não consiga eu te contato.
