### ISSUE TITLE
Sugestões para padronização do repositório

### ISSUE THREAD

**Issue by viniciuscosmome** [PedroHMeireles2001/GamifyHealth#3]
Como seu projeto é **_open-source_** sugiro criar alguns padrões além dos padrões de pastas.

**Commit**
Com um padrão de commit é fácil de entender o contexto e a mudança realizada na marcação. Tem um pacote do node que é só adicionar nas dependências de desenvolvimento do teu projeto que ele te ajuda com isso.
(ver: [git-commit-msg-linter](https://www.npmjs.com/package/git-commit-msg-linter))

**Issues**
As issues podem ser abertas para sugerir mudanças, relatar problemas encontrados, etc. Existe um modo de você criar modelos de issues que o pessoal pode usar quando for abrir uma nova. Esses modelos são como formulários e você pode criar um para cada tipo como problemas (bug), funcionalidades (features) ou documentação (docs, documentation).
(ver: [github-configuring-issue-templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository))

**Pull-request**
Assim como as issues, as pull-requests que criarem para o teu repositório podem seguir um padrão, ou apenas para "dar um norte" para quem não sabe o que escrever na descrição da PR. Porém, os modelos das pull-requests não tem os formulários igual as issues, não que eu saiba hahaha.
(ver: [creating-a-pull-request-template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository))

- criar um guia de como contribuir no seu repo "CONTRIBUTING.md". ([exemplo](https://github.com/github/docs/blob/main/CONTRIBUTING.md))
- adicionar um linter no seu projeto para manter um padrão de código. ([exemplo: eslint](https://eslint.org/))
...

Bom, vou sugerir somente esses.... Ah! Se quiser podemos usar esta issue para discutir algum padrão de issue ou PR pra ti 😉

**Comment by PedroHMeireles2001** [comment]
Sou iniciante em GIT, vou dar uma estudada nas padronizações antes de fazer qualquer coisa.
Obrigado pela dica <3

**Comment by viniciuscosmome** [comment]
show! vai te ajudar bastante estudar o git. Vou fechar a issue, mas tu abre novamente se quiser falar mais sobre.
